# Generated by Django 4.2.11 on 2024-03-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotwheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('year_released', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Terminada'), ('upcoming', 'Por hacer')], default='upcoming', max_length=10)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotwheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.hotwheel')),
            ],
        ),
    ]
