# Generated by Django 4.2.11 on 2024-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwheel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotwheels/'),
        ),
    ]
