# Generated by Django 4.2.4 on 2024-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(choices=[('Contra entrega', 'Contra entrega'), ('Tarjeta débito', 'Tarjeta débito'), ('Tarjeta crédito', 'Tarjeta crédito')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('En progreso', 'En progreso')], max_length=100),
        ),
    ]
