# Generated by Django 4.2.4 on 2024-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_details_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(choices=[('credito', 'Tarjeta de crédito'), ('debito', 'Tarjeta de débito'), ('transferencia', 'Transferencia'), ('contra_entrega', 'Contra entrega')], max_length=500),
        ),
    ]
